package action.command;

/**
 * Created by Ethan on 16/4/30.
 */
public enum CommandType {
    FIND_WINNER_COMMAND, ERROR_COMMAND, PROMPT_COMMAND, SELL_ESTATE_COMMAND,
    BANKRUPT_COMMAND, ESTATE_EVENT, BONUS_CARD_EVENT, YES_OR_NO_REQUEST, CONTROLLED_DICE_REQUEST
}
